spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=UTC
# REMOVA o espaço após a palavra root
spring.datasource.username=root
# DIGITE a senha do seu MySQL Workbench / Local aqui dentro
spring.datasource.password=

# Driver JDBC do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
